### ISSUE TITLE
Does not run on Windows 10

### ISSUE THREAD

**Issue by nerndt** [MicrosoftEdge/JSBrowser#26]
Is it possible to run this on the new windows 10?  I get the "Error: DEP3320 : Target device's operating system version does not meet the application's minimum requirement. Minimum required operating system is Windows 10.0."

**Comment by hydrosquall** [comment]
+1, not able to run on a clean install of windows 10 either

**Comment by jayrenn** [comment]
Hi @nerndt. Yes, it should run any version of Windows 10 from RTM onward. Can you provide some more details on your build environment? What build of Windows are you using? What version of Visual Studio are you running?

**Comment by Linecommander** [comment]
Well I have got the same problem, I couldn't build or edit anything in the project and that is because of this error that I couldn't get to solve. "To deploy this application, your deployement target should be running Windows Universal Runtime version 10.0.10586  or higher. You currently are running version 10.0.10240.16725, Please update your OS" should I install a more recent version of windows 10?

**Comment by Linecommander** [comment]
Nevermind, i got it to work by updating.
